DROP TABLE IF EXISTS CUSTOMER;
CREATE TABLE CUSTOMER (
    CUSTOMER_ID INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    FIRSTNAME VARCHAR(16) NOT NULL,
    SURNAME VARCHAR(16) NOT NULL,
    BALANCE DOUBLE NOT NULL,
    CREATED TIMESTAMP NOT NULL DEFAULT NOW(),
    UPDATED TIMESTAMP
);

DROP TABLE IF EXISTS ACCOUNT;
CREATE TABLE ACCOUNT (
    ACCOUNT_ID INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    CUSTOMER_ID INT NOT NULL,
    CREATED_ON TIMESTAMP NOT NULL DEFAULT NOW()
);