server:
  port: 8081
spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:accountmngdb
    username: sa
    password:
    driverClassName: org.h2.Driver


  jpa:
    hibernate:
      ddl-auto: none #ensure that the Db will be performed by scripts

logging:
  level:
    org:
      springframework: INFO
    com:
      accountManagement:
        accountmanagement: DEBUG
