INSERT INTO CUSTOMER(ID, FIRST_NAME, SUR_NAME, BALANCE) VALUES(1001,'Mohamed','Elshemy','100');
INSERT INTO CUSTOMER(ID, FIRST_NAME, SUR_NAME, BALANCE) VALUES(1002,'Walter','White','990');
--INSERT INTO ACCOUNT(ID,CUSTOMER_ID) VALUES(2001,1003);
