DROP TABLE IF EXISTS CUSTOMER;
CREATE TABLE CUSTOMER (
    ID INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    FIRST_NAME VARCHAR(16) NOT NULL,
    SUR_NAME VARCHAR(16) NOT NULL,
    BALANCE DOUBLE NOT NULL,
    CREATED TIMESTAMP NOT NULL DEFAULT NOW(),
    UPDATED TIMESTAMP
);

DROP TABLE IF EXISTS ACCOUNT;
CREATE TABLE ACCOUNT (
    ID INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    CUSTOMER_ID INT NOT NULL,
    CREATED TIMESTAMP NOT NULL DEFAULT NOW(),
    CONSTRAINT FK_CUSTOMER_ACCOUNT FOREIGN KEY (CUSTOMER_ID)
            REFERENCES CUSTOMER(ID)
);